/* SPDX-License-Identifier: MIT
 *
 * Fixture-driven pre-tokenizer-program conformance test.
 *
 * packages/pretok-program-conformance/fixtures/pretok-program-cases.json
 * is the cross-language source of truth for pre_tokenizer_program
 * execution: every Codec pretok-program interpreter (TypeScript,
 * Python, Rust, C) must reproduce its 43 cases' piece lists exactly,
 * for both v1 (`ops`) and v2 (`stages`) programs. Every
 * `expected_pieces` entry was generated by actually running
 * packages/web/src/pretok-program.ts, the reference v2 executor, not
 * hand-typed: it cannot silently drift from what that executor does.
 *
 * This file loads the fixture generically and replays every case the
 * same way test_tool_watcher_fixture.c replays the ToolWatcher
 * conformance fixture: a loader that iterates whatever `cases` the
 * fixture contains picks up a new case the moment it lands here, with
 * no second commit required to hand-mirror it into this file.
 *
 * Each case's `program` value is spliced byte-for-byte (it is already
 * well-formed JSON once jsmn has located its token span) into a
 * minimal synthetic TokenizerMap document, then handed to the REAL
 * production parser (codec_map_from_json / map.c's
 * parse_pretok_program) and the REAL production interpreter
 * (codec_pretok_run_program / codec_pretok_run_metaspace). This
 * exercises the exact code path callers use; it does not hand-roll a
 * second parser just for the test.
 *
 * JSON: as in test_tool_watcher_fixture.c, this reads the fixture with
 * the jsmn parser libcodec already vendors (`#define JSMN_HEADER`
 * before including src/jsmn.h, the same idiom codec_safety_policy.c
 * and codec_version_signaling.c use). `json_unescape` below mirrors
 * map.c's static function of the same name (RFC 8259 escapes,
 * including \uXXXX and surrogate pairs): fixture `input` values contain
 * real escapes (newlines, tabs) and raw multi-byte UTF-8 (CJK,
 * combining marks), so the tool-watcher fixture's simpler
 * "fail if any backslash" tok_dup_str is not sufficient here.
 */
#include "codec/codec.h"
#include "codec_test.h"

/* codec_map_pretok_program() is an internal accessor (codec_internal.h,
 * shared with detokenize.c / bpe.c / tool_watcher.c), not part of the
 * public codec.h surface. Without this include, the implicit
 * declaration a C99 compiler falls back to assumes an `int` return,
 * which truncates the returned pointer to 32 bits on a 64-bit target:
 * a real crash-or-garbage bug, not just a style warning. */
#include "codec_internal.h"

#define JSMN_HEADER
#include "jsmn.h"
#include "codec_jsmn_guard.h"

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ── Fixture location ──────────────────────────────────────────────────── */

static const char *g_fixture_path_candidates[] = {
    "../pretok-program-conformance/fixtures/pretok-program-cases.json",
    "../../pretok-program-conformance/fixtures/pretok-program-cases.json",
    "packages/pretok-program-conformance/fixtures/pretok-program-cases.json",
    "pretok-program-conformance/fixtures/pretok-program-cases.json",
};

static char *read_whole_file(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) return NULL;
    if (fseek(f, 0, SEEK_END) != 0) { fclose(f); return NULL; }
    long sz = ftell(f);
    if (sz < 0) { fclose(f); return NULL; }
    if (fseek(f, 0, SEEK_SET) != 0) { fclose(f); return NULL; }
    char *buf = (char *)malloc((size_t)sz + 1);
    if (!buf) { fclose(f); return NULL; }
    size_t got = (sz > 0) ? fread(buf, 1, (size_t)sz, f) : 0;
    fclose(f);
    if (got != (size_t)sz) { free(buf); return NULL; }
    buf[sz] = 0;
    *out_len = (size_t)sz;
    return buf;
}

static char *load_fixture_text(size_t *out_len, const char **out_path) {
    const char *env = getenv("CODEC_PRETOK_FIXTURE_PATH");
    if (env && *env) {
        char *txt = read_whole_file(env, out_len);
        if (txt) { *out_path = env; return txt; }
    }
    size_t n = sizeof(g_fixture_path_candidates) / sizeof(g_fixture_path_candidates[0]);
    for (size_t i = 0; i < n; i++) {
        char *txt = read_whole_file(g_fixture_path_candidates[i], out_len);
        if (txt) { *out_path = g_fixture_path_candidates[i]; return txt; }
    }
    return NULL;
}

/* ── Small jsmn walking helpers (same shapes map.c / test_tool_watcher_
 *    fixture.c use) ──────────────────────────────────────────────────── */

static int tok_eq(const char *json, const jsmntok_t *t, const char *lit) {
    if (t->type != JSMN_STRING && t->type != JSMN_PRIMITIVE) return 0;
    size_t lit_len = strlen(lit);
    size_t tok_len = (size_t)(t->end - t->start);
    if (tok_len != lit_len) return 0;
    return memcmp(json + t->start, lit, lit_len) == 0;
}

static size_t skip_subtree(const jsmntok_t *toks, size_t idx) {
    size_t remaining = 1;
    size_t i = idx;
    while (remaining > 0) {
        const jsmntok_t *t = &toks[i++];
        remaining--;
        if (t->type == JSMN_OBJECT) remaining += (size_t)t->size * 2;
        else if (t->type == JSMN_ARRAY) remaining += (size_t)t->size;
    }
    return i;
}

static int obj_find(const char *json, const jsmntok_t *toks, size_t obj_idx,
                     const char *key, size_t *out_val_idx) {
    const jsmntok_t *obj = &toks[obj_idx];
    size_t pos = obj_idx + 1;
    for (int i = 0; i < obj->size; i++) {
        const jsmntok_t *k = &toks[pos];
        size_t val_idx = pos + 1;
        if (tok_eq(json, k, key)) { *out_val_idx = val_idx; return 1; }
        pos = skip_subtree(toks, val_idx);
    }
    return 0;
}

/* RFC 8259 string unescape. Mirrors map.c's static json_unescape
 * exactly (not reachable from here: file-local to map.c). Returns a
 * freshly-malloced UTF-8 buffer; *out_len is its byte length (not
 * counting the NUL this always appends). Returns NULL on malformed
 * input. */
static int hex_nibble(char c) {
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    return -1;
}
static int hex_byte(char hi, char lo) {
    int h = hex_nibble(hi), l = hex_nibble(lo);
    if (h < 0 || l < 0) return -1;
    return (h << 4) | l;
}
static char *json_unescape(const char *src, size_t src_len, size_t *out_len) {
    char *buf = (char *)malloc(src_len + 1);
    if (!buf) return NULL;
    size_t out = 0, i = 0;
    while (i < src_len) {
        unsigned char c = (unsigned char)src[i];
        if (c != '\\') { buf[out++] = (char)c; i++; continue; }
        if (i + 1 >= src_len) { free(buf); return NULL; }
        char esc = src[i + 1];
        i += 2;
        switch (esc) {
            case '"':  buf[out++] = '"';  break;
            case '\\': buf[out++] = '\\'; break;
            case '/':  buf[out++] = '/';  break;
            case 'b':  buf[out++] = '\b'; break;
            case 'f':  buf[out++] = '\f'; break;
            case 'n':  buf[out++] = '\n'; break;
            case 'r':  buf[out++] = '\r'; break;
            case 't':  buf[out++] = '\t'; break;
            case 'u': {
                if (i + 4 > src_len) { free(buf); return NULL; }
                int hi = hex_byte(src[i], src[i + 1]);
                int lo = hex_byte(src[i + 2], src[i + 3]);
                if (hi < 0 || lo < 0) { free(buf); return NULL; }
                uint32_t cp = ((uint32_t)hi << 8) | (uint32_t)lo;
                i += 4;
                if (cp >= 0xD800 && cp <= 0xDBFF) {
                    if (i + 6 > src_len || src[i] != '\\' || src[i + 1] != 'u') {
                        free(buf); return NULL;
                    }
                    int hi2 = hex_byte(src[i + 2], src[i + 3]);
                    int lo2 = hex_byte(src[i + 4], src[i + 5]);
                    if (hi2 < 0 || lo2 < 0) { free(buf); return NULL; }
                    uint32_t low = ((uint32_t)hi2 << 8) | (uint32_t)lo2;
                    if (low < 0xDC00 || low > 0xDFFF) { free(buf); return NULL; }
                    i += 6;
                    cp = 0x10000 + ((cp - 0xD800) << 10) + (low - 0xDC00);
                }
                if (cp <= 0x7F) {
                    buf[out++] = (char)cp;
                } else if (cp <= 0x7FF) {
                    buf[out++] = (char)(0xC0 | (cp >> 6));
                    buf[out++] = (char)(0x80 | (cp & 0x3F));
                } else if (cp <= 0xFFFF) {
                    buf[out++] = (char)(0xE0 | (cp >> 12));
                    buf[out++] = (char)(0x80 | ((cp >> 6) & 0x3F));
                    buf[out++] = (char)(0x80 | (cp & 0x3F));
                } else {
                    buf[out++] = (char)(0xF0 | (cp >> 18));
                    buf[out++] = (char)(0x80 | ((cp >> 12) & 0x3F));
                    buf[out++] = (char)(0x80 | ((cp >> 6) & 0x3F));
                    buf[out++] = (char)(0x80 | (cp & 0x3F));
                }
                break;
            }
            default:
                free(buf);
                return NULL;
        }
    }
    char *fit = (char *)realloc(buf, out + 1);
    if (fit) buf = fit;
    buf[out] = 0;
    *out_len = out;
    return buf;
}

static char *tok_dup_str(const char *json, const jsmntok_t *t) {
    if (t->type != JSMN_STRING) return NULL;
    size_t len = (size_t)(t->end - t->start);
    for (size_t i = 0; i < len; i++) {
        if (json[t->start + i] == '\\') return NULL;
    }
    char *out = (char *)malloc(len + 1);
    if (!out) return NULL;
    if (len > 0) memcpy(out, json + t->start, len);
    out[len] = 0;
    return out;
}

/* ── Running one fixture case ─────────────────────────────────────────── */

/* Wraps a case's raw `program` JSON bytes in a minimal but valid
 * TokenizerMap document, then loads it through the REAL production
 * parser: this test never constructs a codec_pretok_program_t by hand.
 * `vocab_size`/`vocab` are dummy fields codec_map_from_json's
 * validation requires; BPE is never invoked in this test, only the
 * pretok interpreter. */
static codec_status_t build_map_from_program(
    const char *json, const jsmntok_t *program_tok,
    codec_tokenizer_map_t **out_map)
{
    static const char PREFIX[] =
        "{\"id\":\"fixture/pretok\",\"version\":\"2\",\"vocab_size\":1,"
        "\"vocab\":{\"a\":0},\"encoder\":\"byte_level\","
        "\"pre_tokenizer_program\":";
    static const char SUFFIX[] = "}";

    size_t prog_len = (size_t)(program_tok->end - program_tok->start);
    size_t total = sizeof(PREFIX) - 1 + prog_len + sizeof(SUFFIX) - 1;
    char *wrapper = (char *)malloc(total + 1);
    if (!wrapper) return CODEC_ERR_OUT_OF_MEMORY;

    size_t off = 0;
    memcpy(wrapper + off, PREFIX, sizeof(PREFIX) - 1); off += sizeof(PREFIX) - 1;
    memcpy(wrapper + off, json + program_tok->start, prog_len);  off += prog_len;
    memcpy(wrapper + off, SUFFIX, sizeof(SUFFIX) - 1); off += sizeof(SUFFIX) - 1;

    codec_status_t st = codec_map_from_json(wrapper, off, out_map);
    free(wrapper);
    return st;
}

static void run_case(const char *json, const jsmntok_t *toks, size_t case_idx) {
    size_t name_idx, program_idx, input_idx, expected_idx;
    if (!obj_find(json, toks, case_idx, "name", &name_idx)
        || !obj_find(json, toks, case_idx, "program", &program_idx)
        || !obj_find(json, toks, case_idx, "input", &input_idx)
        || !obj_find(json, toks, case_idx, "expected_pieces", &expected_idx)) {
        CT_FAIL("case at token %zu: missing name/program/input/expected_pieces", case_idx);
        return;
    }

    char *name = tok_dup_str(json, &toks[name_idx]);
    const char *name_disp = name ? name : "(unnamed)";

    size_t input_len;
    char *input = json_unescape(json + toks[input_idx].start,
                                (size_t)(toks[input_idx].end - toks[input_idx].start),
                                &input_len);
    if (!input) {
        CT_FAIL("case \"%s\": bad \"input\" string", name_disp);
        free(name);
        return;
    }

    /* Expected pieces: unescape each element up front. */
    const jsmntok_t *exp_arr = &toks[expected_idx];
    size_t n_expected = (size_t)exp_arr->size;
    char **expected = (char **)calloc(n_expected ? n_expected : 1, sizeof(char *));
    size_t *expected_len = (size_t *)calloc(n_expected ? n_expected : 1, sizeof(size_t));
    size_t epos = expected_idx + 1;
    for (size_t k = 0; k < n_expected; k++) {
        expected[k] = json_unescape(json + toks[epos].start,
                                    (size_t)(toks[epos].end - toks[epos].start),
                                    &expected_len[k]);
        if (!expected[k]) CT_FAIL("case \"%s\": bad expected_pieces[%zu]", name_disp, k);
        epos = skip_subtree(toks, epos);
    }

    codec_tokenizer_map_t *map = NULL;
    codec_status_t st = build_map_from_program(json, &toks[program_idx], &map);
    if (st != CODEC_OK) {
        CT_FAIL("case \"%s\": building/parsing the synthetic map failed: %s",
                name_disp, codec_status_str(st));
        goto cleanup;
    }

    const codec_pretok_program_t *prog = codec_map_pretok_program(map);
    if (!prog) {
        CT_FAIL("case \"%s\": map has no pretok program after a successful parse", name_disp);
        goto cleanup_map;
    }

    int is_metaspace = (prog->version == 1 && prog->op_count == 1
                        && prog->ops[0].kind == CODEC_PRETOK_METASPACE_SPLIT);

    if (is_metaspace) {
        char **pieces = NULL;
        size_t n_pieces = 0;
        st = codec_pretok_run_metaspace((const uint8_t *)input, input_len,
                                        prog->ops[0].u.metaspace_split.prefix_first,
                                        &pieces, &n_pieces);
        if (st != CODEC_OK) {
            CT_FAIL("case \"%s\": codec_pretok_run_metaspace failed: %s",
                    name_disp, codec_status_str(st));
            goto cleanup_map;
        }
        if (n_pieces != n_expected) {
            CT_FAIL("case \"%s\": piece count mismatch: actual=%zu expected=%zu",
                    name_disp, n_pieces, n_expected);
        } else {
            for (size_t k = 0; k < n_pieces; k++) {
                if (strlen(pieces[k]) != expected_len[k]
                    || memcmp(pieces[k], expected[k], expected_len[k]) != 0) {
                    CT_FAIL("case \"%s\": piece[%zu] mismatch: actual=\"%s\" expected=\"%.*s\"",
                            name_disp, k, pieces[k], (int)expected_len[k], expected[k]);
                }
            }
        }
        codec_pretok_free_metaspace_pieces(pieces, n_pieces);
    } else {
        codec_pretok_piece_t *pieces = NULL;
        size_t n_pieces = 0;
        st = codec_pretok_run_program(prog, (const uint8_t *)input, input_len,
                                      &pieces, &n_pieces);
        if (st != CODEC_OK) {
            CT_FAIL("case \"%s\": codec_pretok_run_program failed: %s",
                    name_disp, codec_status_str(st));
            goto cleanup_map;
        }
        if (n_pieces != n_expected) {
            CT_FAIL("case \"%s\": piece count mismatch: actual=%zu expected=%zu",
                    name_disp, n_pieces, n_expected);
            for (size_t k = 0; k < n_pieces; k++) {
                fprintf(stderr, "    actual[%zu] = \"%.*s\"\n",
                        k, (int)pieces[k].len, input + pieces[k].off);
            }
        } else {
            for (size_t k = 0; k < n_pieces; k++) {
                if (pieces[k].len != expected_len[k]
                    || memcmp(input + pieces[k].off, expected[k], expected_len[k]) != 0) {
                    CT_FAIL("case \"%s\": piece[%zu] mismatch: actual=\"%.*s\" expected=\"%.*s\"",
                            name_disp, k, (int)pieces[k].len, input + pieces[k].off,
                            (int)expected_len[k], expected[k]);
                }
            }
        }
        codec_pretok_free_pieces(pieces);
    }

cleanup_map:
    codec_map_free(map);
cleanup:
    for (size_t k = 0; k < n_expected; k++) free(expected[k]);
    free(expected);
    free(expected_len);
    free(input);
    free(name);
}

/* ── main ─────────────────────────────────────────────────────────────── */

int main(void) {
    size_t json_len = 0;
    const char *used_path = NULL;
    char *json = load_fixture_text(&json_len, &used_path);
    if (!json) {
        CT_FAIL("could not locate pretok-program-cases.json "
                "(checked CODEC_PRETOK_FIXTURE_PATH and relative fallbacks); "
                "set CODEC_PRETOK_FIXTURE_PATH to override");
        CT_DONE();
    }
    fprintf(stdout, "fixture: %s\n", used_path);

    jsmn_parser p;
    jsmn_init(&p);
    int ntok = jsmn_parse(&p, json, json_len, NULL, 0);
    if (ntok < 0) {
        CT_FAIL("jsmn_parse (count pass) failed: %d", ntok);
        free(json);
        CT_DONE();
    }
    jsmntok_t *toks = (jsmntok_t *)malloc(sizeof(jsmntok_t) * (size_t)(ntok > 0 ? ntok : 1));
    if (!toks) {
        CT_FAIL("out of memory allocating %d jsmn tokens", ntok);
        free(json);
        CT_DONE();
    }
    jsmn_init(&p);
    ntok = jsmn_parse(&p, json, json_len, toks, (unsigned int)ntok);
    if (ntok < 0) {
        CT_FAIL("jsmn_parse (fill pass) failed: %d", ntok);
        free(toks);
        free(json);
        CT_DONE();
    }
    if (!codec_jsmn_tree_complete(toks, (size_t)ntok)) {
        CT_FAIL("fixture JSON failed the jsmn structural-completeness check");
        free(toks);
        free(json);
        CT_DONE();
    }
    if (ntok == 0 || toks[0].type != JSMN_OBJECT) {
        CT_FAIL("fixture root is not a JSON object");
        free(toks);
        free(json);
        CT_DONE();
    }

    size_t cases_idx;
    if (!obj_find(json, toks, 0, "cases", &cases_idx)) {
        CT_FAIL("fixture is missing \"cases\" at the top level");
        free(toks);
        free(json);
        CT_DONE();
    }
    const jsmntok_t *cases_tok = &toks[cases_idx];
    if (cases_tok->type != JSMN_ARRAY) {
        CT_FAIL("fixture \"cases\" is not an array");
        free(toks);
        free(json);
        CT_DONE();
    }

    size_t n_cases = (size_t)cases_tok->size;
    fprintf(stdout, "fixture cases: %zu\n", n_cases);
    /* A loader that silently accepts zero cases would "pass" vacuously
     * and defeat the whole point of this file. */
    CT_TRUE(n_cases > 0);

    size_t pos = cases_idx + 1;
    for (size_t ci = 0; ci < n_cases; ci++) {
        int before = _codec_test_failures;
        run_case(json, toks, pos);
        int delta = _codec_test_failures - before;
        fprintf(stdout, "%s fixture_case[%zu]\n", delta == 0 ? "PASS" : "FAIL", ci);
        pos = skip_subtree(toks, pos);
    }

    free(toks);
    free(json);
    CT_DONE();
}
