// SPDX-License-Identifier: MIT
package ai.codec;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Per-model tool-calling convention block on a {@link TokenizerMap}. Carries
 * how the model packages tool calls and how it expects results back: the
 * structural layer above {@code special_tokens}. Generated by
 * {@code @codecai/maps-cli} from the model's chat template.
 *
 * <p>Each {@code convention} value pins a specific argument layout, marker
 * placement, and result framing. See {@code spec/PROTOCOL.md} §
 * "Tool-call calling conventions in the map" for the normative table; the
 * registry of valid values is closed (additive point releases of the
 * schema only).
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class ToolCallingBlock {

    /**
     * Closed enum naming the calling convention. {@code "custom"} opts out of
     * the registry; implementations using {@code "custom"} MUST pin the layout
     * in implementer-supplied prose and MUST NOT assume registry semantics.
     */
    public enum Convention {
        LLAMA3("llama3"),
        QWEN25("qwen25"),
        PHI4("phi4"),
        MISTRAL_NEMO("mistral_nemo"),
        DEEPSEEK_V3("deepseek_v3"),
        DEEPSEEK_R1("deepseek_r1"),
        CUSTOM("custom");

        private final String wire;

        Convention(String wire) { this.wire = wire; }

        @com.fasterxml.jackson.annotation.JsonValue
        public String wire() { return wire; }

        @JsonCreator
        public static Convention fromWire(String value) {
            if (value == null) return null;
            for (Convention c : values()) {
                if (c.wire.equals(value)) return c;
            }
            throw new TokenizerMapValidationException(
                "tool_calling.convention must be one of [llama3, qwen25, phi4, "
                + "mistral_nemo, deepseek_v3, deepseek_r1, custom], got \"" + value + "\"");
        }
    }

    public enum ArgsFormat {
        JSON("json"),
        PYTHON_ARGS("python_args");

        private final String wire;
        ArgsFormat(String wire) { this.wire = wire; }
        @com.fasterxml.jackson.annotation.JsonValue
        public String wire() { return wire; }
        @JsonCreator
        public static ArgsFormat fromWire(String value) {
            if (value == null) return null;
            for (ArgsFormat f : values()) if (f.wire.equals(value)) return f;
            throw new TokenizerMapValidationException(
                "tool_calling.args_format must be one of [json, python_args], got \"" + value + "\"");
        }
    }

    public enum ResultFormat {
        TEXT("text"),
        JSON("json");

        private final String wire;
        ResultFormat(String wire) { this.wire = wire; }
        @com.fasterxml.jackson.annotation.JsonValue
        public String wire() { return wire; }
        @JsonCreator
        public static ResultFormat fromWire(String value) {
            if (value == null) return null;
            for (ResultFormat f : values()) if (f.wire.equals(value)) return f;
            throw new TokenizerMapValidationException(
                "tool_calling.result_format must be one of [text, json], got \"" + value + "\"");
        }
    }

    /** Start/end marker token names. Both names MUST exist as keys in the
     *  parent map's {@code special_tokens} object. */
    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public static final class Markers {
        @JsonProperty("start")
        public String start;
        @JsonProperty("end")
        public String end;

        public Markers() {}
        public Markers(String start, String end) { this.start = start; this.end = end; }
    }

    @JsonProperty("convention")
    public Convention convention;

    @JsonProperty("markers")
    public Markers markers;

    @JsonProperty("args_format")
    public ArgsFormat argsFormat;

    @JsonProperty("result_format")
    public ResultFormat resultFormat;

    public ToolCallingBlock() {}
}
