// SPDX-License-Identifier: MIT
//
// PickerConformanceTests.cs — replay the cross-language picker vector
// set against the .NET port and assert byte-for-byte parity with the
// TypeScript reference (packages/wire-compress/src/index.ts).
//
// The vector file is generated by:
//   node packages/wire-compress/test/generate-conformance-vectors.mjs
// and lives at packages/wire-compress/test/conformance-vectors.json.
//
// CI fails if any case diverges. If the vector file isn't checked out
// (sparse clone, separated package layout), the conformance test is
// skipped so the rest of the suite stays green.

using System;
using System.IO;
using System.Text.Json;
using Codec.Wire;
using Xunit;
using Xunit.Sdk;

namespace Codec.Net.Tests;

public class PickerConformanceTests
{
    [SkippableFact]
    public void Replay_ConformanceVectors_MatchesTypescriptReference()
    {
        string? vectorsPath = ResolveVectorsPath();
        Skip.If(vectorsPath is null,
            "conformance-vectors.json not found; run "
            + "`node packages/wire-compress/test/generate-conformance-vectors.mjs` "
            + "from a full Codec checkout.");

        using var fs = File.OpenRead(vectorsPath!);
        var doc = JsonDocument.Parse(fs);
        var root = doc.RootElement;

        // Pre-compute the two sample byte profiles. The TS generator
        // produces deterministic samples via xorshift32 + bundles them
        // base64 in the JSON so cross-language runners use byte-identical
        // bytes — we read them from the bundled payload.
        var samples = root.GetProperty("samples");
        var lowEntropy = Convert.FromBase64String(samples.GetProperty("low-entropy").GetString()!);
        var highEntropy = Convert.FromBase64String(samples.GetProperty("high-entropy").GetString()!);

        int total = 0;
        int divergent = 0;
        var firstDivergences = new System.Text.StringBuilder();

        foreach (var v in root.GetProperty("vectors").EnumerateArray())
        {
            total++;
            string? accept = v.GetProperty("accept_encoding").ValueKind == JsonValueKind.Null
                ? null
                : v.GetProperty("accept_encoding").GetString();
            int size = v.GetProperty("estimated_size").GetInt32();
            bool interactive = v.GetProperty("interactive").GetBoolean();
            bool hasDict = v.GetProperty("zstd_has_dict").GetBoolean();
            bool enabled = v.GetProperty("zstd_enabled").GetBoolean();
            string? stackName = v.GetProperty("stack_profile").ValueKind == JsonValueKind.Null
                ? null
                : v.GetProperty("stack_profile").GetString();
            string sampleId = v.GetProperty("sample").GetString()!;
            string expectEnc = v.GetProperty("expect_encoding").GetString()!;
            string expectReason = v.GetProperty("expect_reason_code").GetString()!;

            byte[]? sampleBytes = sampleId switch
            {
                "low-entropy" => lowEntropy,
                "high-entropy" => highEntropy,
                _ => null,
            };

            var input = new PickInput
            {
                AcceptEncoding = accept,
                EstimatedSize = size,
                Interactive = interactive,
                ZstdHasDict = hasDict,
                ZstdEnabled = enabled,
                StackProfile = stackName is null
                    ? StackProfiles.Default
                    : StackProfiles.For(stackName),
                // Explicit null check — the byte[] → ReadOnlyMemory<byte>
                // implicit conversion turns `null` into empty ROM (not
                // null), which would trip the content-aware tiebreaker.
                SampleBytes = sampleBytes is null
                    ? (ReadOnlyMemory<byte>?)null
                    : new ReadOnlyMemory<byte>(sampleBytes),
            };
            var r = Picker.Pick(input);
            var gotEnc = Picker.EncodingName(r.Encoding);
            var gotReason = Picker.ReasonCodeName(r.ReasonCode);

            if (gotEnc != expectEnc || gotReason != expectReason)
            {
                divergent++;
                if (divergent <= 10)
                {
                    firstDivergences.AppendLine(
                        $"  vector {v.GetProperty("id").GetInt32()}: "
                        + $"accept={accept ?? "(null)"} size={size} interactive={interactive} "
                        + $"has_dict={hasDict} enabled={enabled} "
                        + $"stack={stackName ?? "(default)"} sample={sampleId}\n"
                        + $"    expect: enc={expectEnc} reason={expectReason}\n"
                        + $"    got:    enc={gotEnc} reason={gotReason}");
                }
            }
        }

        Assert.True(divergent == 0,
            $"{divergent} / {total} vectors diverged from TS reference:\n"
            + firstDivergences.ToString());
    }

    /// <summary>
    /// Try a few likely locations for the vectors file:
    ///   1. CODEC_WIRE_CONFORMANCE_VECTORS env var (CI sets this).
    ///   2. Walk up from this test binary to packages/wire-compress/test/.
    ///   3. Walk up looking for a packages/ sibling directory.
    /// Returns null when nothing is found (the SkippableFact will skip).
    /// </summary>
    private static string? ResolveVectorsPath()
    {
        var env = Environment.GetEnvironmentVariable("CODEC_WIRE_CONFORMANCE_VECTORS");
        if (!string.IsNullOrEmpty(env) && File.Exists(env)) return env;

        // Walk up from AppContext.BaseDirectory looking for
        // packages/wire-compress/test/conformance-vectors.json
        var dir = AppContext.BaseDirectory;
        for (int i = 0; i < 8 && dir is not null; i++)
        {
            var candidate = Path.Combine(dir, "packages", "wire-compress", "test", "conformance-vectors.json");
            if (File.Exists(candidate)) return candidate;
            // also try one-level inner (some test runners drop into bin/Debug/...)
            var parent = Directory.GetParent(dir);
            dir = parent?.FullName;
        }
        return null;
    }
}
