#!/usr/bin/env python3
"""Picker bench harness — exercises @codecai/wire-compress's pick() across
the realistic space of (stack profile, payload size, sample entropy, gate
state) combinations and records which reason_code fires for each cell.

v0.5 task #49. Companion to #46 (the picker rewrite). The rewrite added a
typed `reason_code` enum on pick() output so dashboards can group outcomes
without parsing free text; this harness verifies every documented
reason_code value is actually reachable, and produces a coverage matrix
that demos how the picker decides across realistic inputs.

Two output modes:

  1. Coverage matrix (always) — runs the picker on a grid of inputs and
     writes a per-cell JSON with the chosen encoding + reason_code. The
     grid covers:
       - 3 stack profiles (default, sglang, custom-buffered-zstd)
       - 4 payload sizes (small / medium / large / huge)
       - 3 sample-entropy buckets (none / low / high)
       - 4 gate states (zstdHasDict × zstdEnabled cross-product)

  2. Real-traffic mode (--from-sglang=<sample-dir>) — opt-in. Reads a
     directory of real sglang response samples produced by
     `capture-codec-samples.py`, runs the picker against each, and
     compares the picker's choice to the bytes-actually-smallest choice
     (which encoding would have shipped the fewest bytes on this
     payload). Identifies picker mis-pricings.

Run:
  npx tsc -p packages/wire-compress/tsconfig.json   # build wire-compress first
  python packages/bench/scripts/picker_bench.py \\
      --output packages/bench/results/<UTC>/picker/

  # With real captures (also needs the v0.5 picker rewrite built):
  python packages/bench/scripts/picker_bench.py \\
      --output packages/bench/results/<UTC>/picker/ \\
      --from-sglang packages/bench/results/<UTC>/sglang/samples/
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from itertools import product
from pathlib import Path
from typing import Any


# ── grid axes ──────────────────────────────────────────────────────────────

STACK_PROFILES = ["default", "sglang", "custom-buffered-zstd"]
PAYLOAD_SIZES = [128, 1024, 8192, 32768]
ENTROPY_BUCKETS = ["none", "low", "high"]
GATE_STATES = list(product([True, False], [True, False]))  # (hasDict, enabled)

# Reasonable subset of Accept-Encoding headers to exercise the picker.
ACCEPT_HEADERS = [
    "zstd, gzip, br",   # modern browser / Chrome 123+
    "gzip, br",         # older browser / Safari
    "gzip",             # minimal client
    "",                 # identity-only client
]


def make_picker_runner() -> Path:
    """Create a small Node shim that loads the picker + exposes a stdin loop.

    The shim reads JSON-lines from stdin and writes JSON-lines to stdout —
    one Node process handles the entire batch instead of paying Node
    startup cost per cell. Written once next to the script; idempotent.
    """
    here = Path(__file__).parent.parent / "picker_bench_shim.mjs"
    here.write_text(
        '#!/usr/bin/env node\n'
        '// Generated by picker_bench.py — do not edit directly.\n'
        'import {pick, profileFor, MAX_TTFT_RATIO} from "@codecai/wire-compress";\n'
        'import {createInterface} from "node:readline";\n'
        '\n'
        'function resolveStackProfile(name) {\n'
        '  if (name === "custom-buffered-zstd") {\n'
        '    return {\n'
        '      name: "custom-buffered-zstd",\n'
        '      encodings: {\n'
        '        gzip: { wireCoeff: 0.05, ttftRatio: 1.0 },\n'
        '        br:   { wireCoeff: 0.5,  ttftRatio: 1.0 },\n'
        '        zstd: { wireCoeff: 0.05, ttftRatio: MAX_TTFT_RATIO + 100 },\n'
        '      },\n'
        '    };\n'
        '  }\n'
        '  if (typeof name === "string") return profileFor(name);\n'
        '  return undefined;\n'
        '}\n'
        '\n'
        'function processOne(inp) {\n'
        '  let sampleBytes;\n'
        '  if (inp.sampleBytesB64) {\n'
        '    const buf = Buffer.from(inp.sampleBytesB64, "base64");\n'
        '    sampleBytes = new Uint8Array(buf.buffer, buf.byteOffset, buf.byteLength);\n'
        '  }\n'
        '  return pick({\n'
        '    acceptEncoding: inp.acceptEncoding,\n'
        '    estimatedSize: inp.estimatedSize,\n'
        '    zstdHasDict: inp.zstdHasDict,\n'
        '    zstdEnabled: inp.zstdEnabled,\n'
        '    stackProfile: resolveStackProfile(inp.stackProfile),\n'
        '    sampleBytes,\n'
        '  });\n'
        '}\n'
        '\n'
        'const rl = createInterface({input: process.stdin, terminal: false});\n'
        'rl.on("line", (line) => {\n'
        '  if (!line.trim()) return;\n'
        '  try {\n'
        '    const out = processOne(JSON.parse(line));\n'
        '    process.stdout.write(JSON.stringify(out) + "\\n");\n'
        '  } catch (e) {\n'
        '    process.stdout.write(JSON.stringify({error: String(e)}) + "\\n");\n'
        '  }\n'
        '});\n'
    )
    return here


def call_picker_batch(shim: Path, payloads: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Stream all payloads through one Node process — pay startup cost once."""
    input_lines = "\n".join(json.dumps(p) for p in payloads) + "\n"
    proc = subprocess.run(
        ["npx", "tsx", str(shim)],
        input=input_lines, capture_output=True, text=True, timeout=120,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"shim failed: {proc.stderr}")
    out: list[dict[str, Any]] = []
    for line in proc.stdout.strip().split("\n"):
        if line:
            out.append(json.loads(line))
    return out


def make_sample(entropy_bucket: str) -> bytes | None:
    """Synthetic content sample with the requested entropy."""
    if entropy_bucket == "none":
        return None
    if entropy_bucket == "low":
        return b"A" * 256                                # entropy ≈ 0
    if entropy_bucket == "high":
        return bytes((i * 31 + 17) & 0xff for i in range(256))  # entropy ≈ 8
    raise ValueError(entropy_bucket)


def run_coverage_grid(shim: Path, out_dir: Path) -> dict[str, Any]:
    """Run the picker across the full input grid; record per-cell reasons."""
    import base64
    payloads: list[dict[str, Any]] = []
    cell_keys: list[dict[str, Any]] = []
    for stack, size, entropy, gates, accept in product(
        STACK_PROFILES, PAYLOAD_SIZES, ENTROPY_BUCKETS, GATE_STATES, ACCEPT_HEADERS,
    ):
        has_dict, enabled = gates
        sample = make_sample(entropy)
        payload = {
            "acceptEncoding": accept,
            "estimatedSize": size,
            "zstdHasDict": has_dict,
            "zstdEnabled": enabled,
            "stackProfile": stack,
        }
        if sample:
            payload["sampleBytesB64"] = base64.b64encode(sample).decode("ascii")
        payloads.append(payload)
        cell_keys.append({
            "stack": stack, "size": size, "entropy": entropy,
            "has_dict": has_dict, "enabled": enabled, "accept": accept,
        })

    results = call_picker_batch(shim, payloads)
    seen_reason_codes: set[str] = set()
    cells: list[dict[str, Any]] = []
    for key, result in zip(cell_keys, results):
        cells.append({
            **key,
            "encoding": result.get("encoding"),
            "reason_code": result.get("reason_code"),
        })
        if result.get("reason_code"):
            seen_reason_codes.add(result["reason_code"])

    return {
        "schema_version": "1",
        "kind": "picker_bench_coverage",
        "grid_axes": {
            "stack_profiles": STACK_PROFILES,
            "payload_sizes": PAYLOAD_SIZES,
            "entropy_buckets": ENTROPY_BUCKETS,
            "gate_states": [
                {"has_dict": h, "enabled": e} for (h, e) in GATE_STATES
            ],
            "accept_headers": ACCEPT_HEADERS,
        },
        "cells_count": len(cells),
        "reason_codes_seen": sorted(seen_reason_codes),
        "cells": cells,
    }


# ── --from-sglang real-traffic mode (skeleton) ─────────────────────────────


def run_from_real_captures(shim: Path, captures_dir: Path) -> dict[str, Any]:
    """Read .codec sample bytes from `captures_dir/*.bin`, run the picker on each,
    and compare to what was shipped on the wire.

    Each file under `captures_dir/` is expected to be a raw response body
    captured by `capture-codec-samples.py` with a sibling `.meta.json`
    describing the response (stream_format, encoding, has_dict).

    Computes for each capture:
      - what the picker would have chosen
      - what was actually shipped
      - whether the picker agreed with the shipped choice
    """
    import base64
    files = sorted(captures_dir.glob("*.bin"))
    if not files:
        return {
            "schema_version": "1",
            "kind": "picker_bench_real",
            "error": f"no .bin files under {captures_dir}",
            "captures": [],
        }
    payloads: list[dict[str, Any]] = []
    metas: list[dict[str, Any]] = []
    for path in files:
        meta_path = path.with_suffix(".meta.json")
        if not meta_path.is_file():
            continue
        meta = json.loads(meta_path.read_text())
        body = path.read_bytes()
        payloads.append({
            "acceptEncoding": meta.get("accept_encoding", "zstd, gzip, br"),
            "estimatedSize": len(body),
            "zstdHasDict": meta.get("has_dict", True),
            "zstdEnabled": True,
            "stackProfile": meta.get("stack", "sglang"),
            "sampleBytesB64": base64.b64encode(body[:256]).decode("ascii"),
        })
        metas.append({"file": path.name, "meta": meta, "shipped_bytes": len(body)})

    results = call_picker_batch(shim, payloads)
    captures = [
        {
            "file": m["file"],
            "shipped_encoding": m["meta"].get("content_encoding", "unknown"),
            "shipped_bytes": m["shipped_bytes"],
            "picker_encoding": r.get("encoding"),
            "picker_reason_code": r.get("reason_code"),
            "delta_vs_shipped": (
                "agree" if m["meta"].get("content_encoding") == r.get("encoding")
                else "differ"
            ),
        }
        for m, r in zip(metas, results)
    ]
    return {
        "schema_version": "1",
        "kind": "picker_bench_real",
        "captures_dir": str(captures_dir),
        "captures": captures,
    }


# ── CLI ─────────────────────────────────────────────────────────────────────


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    p.add_argument("--output", type=Path, required=True,
                   help="Output directory (created if missing).")
    p.add_argument("--from-sglang", type=Path,
                   help="Optional: directory of real sglang response samples "
                        "to compare against the picker's choice.")
    args = p.parse_args()

    args.output.mkdir(parents=True, exist_ok=True)
    shim = make_picker_runner()

    coverage = run_coverage_grid(shim, args.output)
    (args.output / "coverage.json").write_text(json.dumps(coverage, indent=2))
    print(f"picker_bench: wrote coverage.json ({coverage['cells_count']} cells, "
          f"{len(coverage['reason_codes_seen'])} reason codes seen)")

    if args.from_sglang:
        real = run_from_real_captures(shim, args.from_sglang)
        (args.output / "real-captures.json").write_text(json.dumps(real, indent=2))
        n = len(real.get("captures", []))
        agree = sum(1 for c in real.get("captures", []) if c.get("delta_vs_shipped") == "agree")
        print(f"picker_bench: wrote real-captures.json ({n} captures, {agree} agree with picker)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
