/**
 * Public types for @codecai/web.
 *
 * A `TokenizerMap` is a per-model dialect — the data needed to encode text
 * into token IDs (for input) and decode IDs back to text (for output). Maps
 * are immutable once published; a new model version publishes a new map at a
 * new URL with a new sha256 hash.
 *
 * Schema version 2 (breaking change from v1):
 *   - `tokens` is replaced by `vocab` (raw form, used by the BPE tokenizer)
 *   - `encoder` describes how raw vocab tokens map to bytes/chars
 *   - `merges` and `pre_tokenizer_pattern` enable client-side BPE encoding
 */

/**
 * A tokenizer dialect for one model (or one model family that shares a
 * tokenizer). Loaded lazily by the client and cached by (id, hash).
 */
export interface TokenizerMap {
  /** Stable, globally unique tokenizer identifier (e.g. `meta-llama/llama-3`). */
  readonly id: string;

  /**
   * Schema version of this map file. Currently `"2"`. Maps with `version="1"`
   * use the legacy `tokens` field and are accepted by the Detokenizer for
   * backwards compatibility but cannot be used by the BPE tokenizer.
   */
  readonly version: string;

  /** Total number of token IDs in the vocabulary. */
  readonly vocab_size: number;

  /**
   * Vocabulary as `{ raw_token_text: id }`. "Raw" means the form stored in
   * HuggingFace `tokenizer.json` — for `byte_level` encoding this contains
   * GPT-2 byte-encoded characters (`Ġ`, etc.); for `metaspace` it contains
   * `▁`-prefixed strings. The Detokenizer applies the appropriate decoder
   * to recover human-readable text.
   */
  readonly vocab?: Readonly<Record<string, number>>;

  /**
   * Legacy v1 vocabulary as `{ decoded_text: id_string }`. Present only on
   * v1 maps. New maps use `vocab` instead.
   */
  readonly tokens?: Readonly<Record<string, string>>;

  /**
   * How vocab tokens are encoded:
   *   - `"byte_level"` — GPT-2 byte→unicode mapping (Llama-3, Qwen, Phi-3, …).
   *   - `"metaspace"`  — `▁` represents a space prefix (SentencePiece-style:
   *                      Llama-2, Mistral-v3, Mixtral, Gemma).
   *   - omitted        — identity (vocab is already decoded text; used by
   *                      simple/test maps and v1 maps).
   */
  readonly encoder?: 'byte_level' | 'metaspace';

  /**
   * BPE merges in priority order. Each entry is two tokens separated by a
   * single space, e.g. `"Ġ a"`. Required by `BPETokenizer`.
   */
  readonly merges?: readonly string[];

  /**
   * Regex pattern that splits input text into pieces before byte-encoding
   * and BPE merging. Required by `BPETokenizer` when `encoder === "byte_level"`
   * unless `pre_tokenizer_program` is present (program is preferred).
   */
  readonly pre_tokenizer_pattern?: string;

  /**
   * Compiled pre-tokenizer program. Preferred over `pre_tokenizer_pattern`
   * when both are present. The program is a small ordered op list that
   * runtimes can execute without a Unicode regex engine — see
   * `spec/PRETOKENIZER_PROGRAM.md` for the schema and op set.
   */
  readonly pre_tokenizer_program?: {
    readonly version: number;
    readonly ops: ReadonlyArray<Readonly<Record<string, unknown>>>;
  };

  /** First ID in the byte-fallback range (inclusive). SentencePiece only. */
  readonly byte_fallback_start?: number;
  /** Last ID in the byte-fallback range (inclusive). SentencePiece only. */
  readonly byte_fallback_end?: number;

  /** Named special tokens. Skipped during text rendering by default. */
  readonly special_tokens?: Readonly<Record<string, number>>;

  /**
   * Per-model tool-calling convention. Optional; populated by
   * `@codecai/maps-cli` when it detects a known chat template signature
   * in `tokenizer_config.json`. Absence means "convention not declared
   * in this map; consult the prose table in spec/PROTOCOL.md
   * § Tool-call detection without decoding."
   *
   * The `markers.start` and `markers.end` strings MUST appear as keys
   * in `special_tokens` — the values are the IDs ToolWatcher compares
   * against. See `spec/PROTOCOL.md § Tool-call calling conventions in
   * the map` for the normative definition of each `convention` value.
   */
  readonly tool_calling?: ToolCallingBlock;

  readonly published_at?: string;
}

/**
 * Per-model tool-calling convention block on a tokenizer map.
 * Carries how the model packages tool calls and how it expects results
 * back — the structural layer above `special_tokens`. Generated by
 * `@codecai/maps-cli` from the model's chat template.
 */
export interface ToolCallingBlock {
  /**
   * Closed enum naming the calling convention. Each value pins a
   * specific argument layout, marker placement, and result framing.
   * `"custom"` opts out of the registry; using `"custom"` requires
   * implementer-supplied prose.
   */
  readonly convention:
    | 'llama3'
    | 'qwen25'
    | 'phi4'
    | 'mistral_nemo'
    | 'deepseek_v3'
    | 'deepseek_r1'
    | 'custom';

  /**
   * Start and end marker tokens. Both names MUST exist as keys in the
   * parent map's `special_tokens` object.
   */
  readonly markers: {
    readonly start: string;
    readonly end: string;
  };

  /**
   * How tool-call arguments are packed inside the marker pair on the
   * engine's output side.
   *
   *   - `"json"`        — a single JSON object, e.g. `{"location":"NYC"}`.
   *   - `"python_args"` — a Python-style call expression. Used by
   *                       Llama-3's `<|python_tag|>` convention.
   */
  readonly args_format: 'json' | 'python_args';

  /**
   * How tool results come back into the model's input.
   *
   *   - `"text"` — opaque UTF-8 text returned verbatim.
   *   - `"json"` — a JSON value (object, array, or scalar) the model parses.
   */
  readonly result_format: 'text' | 'json';
}

/**
 * Wire frame produced by a Codec-compliant server. Identical shape across
 * MessagePack and Protobuf modes — only the serialization differs.
 */
export interface CodecFrame {
  readonly ids: readonly number[];
  readonly done: boolean;
  readonly finish_reason?: string;
}

/**
 * Pluggable cache for loaded maps. Default is in-memory; browsers can pass a
 * Cache API adapter, Node can pass a file-system adapter, etc.
 */
export interface MapCache {
  get(key: string): Promise<TokenizerMap | undefined>;
  set(key: string, map: TokenizerMap): Promise<void>;
}

/**
 * Common interface every tokenizer implementation satisfies. `BPETokenizer`,
 * `LongestMatchTokenizer`, and any wasm/native adapter all implement this.
 */
export interface Tokenizer {
  readonly id: string;
  encode(text: string): number[];
}
