"""Core types for the Codec protocol.

A `TokenizerMap` is a per-model tokenizer dialect — the data needed to encode
text into token IDs and decode IDs back to text. Maps are immutable once
published; a new model version publishes a new map at a new URL with a new
sha256 hash.
"""
from __future__ import annotations

import abc
import json
from dataclasses import dataclass, field
from typing import Any


class TokenizerMapValidationError(ValueError):
    """Raised when a tokenizer map fails the schema check."""

    def __init__(self, message: str) -> None:
        super().__init__(f"TokenizerMap validation failed: {message}")


@dataclass(frozen=True, slots=True)
class CodecFrame:
    """One streaming frame produced by a Codec-compliant server.

    Identical shape across MessagePack and Protobuf wire modes; only
    serialization differs.
    """

    ids: tuple[int, ...]
    """Token IDs emitted by the model in this chunk."""

    done: bool
    """``True`` on the final frame — no further frames follow."""

    finish_reason: str | None = None
    """Set on the final frame. e.g. ``"length"``, ``"stop"``, ``"eos_token"``, ``"error"``."""


_TOOL_CALLING_CONVENTIONS = frozenset({
    "llama3", "qwen25", "phi4", "mistral_nemo",
    "deepseek_v3", "deepseek_r1", "custom",
})
_TOOL_CALLING_ARGS_FORMATS = frozenset({"json", "python_args"})
_TOOL_CALLING_RESULT_FORMATS = frozenset({"text", "json"})


@dataclass(frozen=True, slots=True)
class ToolCallingMarkers:
    """Start/end marker token names for a tool call. Both names MUST exist as
    keys in the parent map's :attr:`TokenizerMap.special_tokens`.
    """
    start: str
    end: str


@dataclass(frozen=True, slots=True)
class ToolCallingBlock:
    """Per-model tool-calling convention from a TokenizerMap.

    Carries how the model packages tool calls and how it expects results back —
    the structural layer above ``special_tokens``. Generated by
    ``@codecai/maps-cli`` from the model's chat template. See
    ``spec/PROTOCOL.md`` § "Tool-call calling conventions in the map".
    """
    convention: str
    """One of ``llama3 | qwen25 | phi4 | mistral_nemo | deepseek_v3 |
    deepseek_r1 | custom``."""

    markers: ToolCallingMarkers
    """Start/end marker token names. Both names MUST exist in
    :attr:`TokenizerMap.special_tokens`."""

    args_format: str
    """``"json"`` or ``"python_args"``."""

    result_format: str
    """``"text"`` or ``"json"``."""


@dataclass(frozen=True)
class TokenizerMap:
    """A per-model tokenizer dialect.

    Schema v2: :attr:`vocab` is the raw HuggingFace tokenizer.json form
    (byte-level GPT-2-encoded chars or ▁-prefixed metaspace strings).
    :attr:`tokens` is the legacy v1 field, kept for backwards compatibility —
    the Detokenizer reads from whichever is present.
    """

    id: str
    """Stable, globally unique tokenizer identifier (e.g. ``"qwen/qwen2"``)."""

    version: str
    """Schema version. ``"2"`` for v2 maps; ``"1"`` for legacy v1."""

    vocab_size: int
    """Total number of token IDs in the vocabulary."""

    vocab: dict[str, int] | None = None
    """Vocabulary as ``{ raw_token_text: id }``. v2 schema field."""

    tokens: dict[str, str] | None = None
    """Legacy v1 vocabulary as ``{ id_string: decoded_text }``."""

    encoder: str | None = None
    """Encoder family: ``"byte_level"``, ``"metaspace"``, or ``None`` (identity)."""

    merges: list[str] | None = None
    """BPE merges in priority order. Each entry is ``"left right"``."""

    pre_tokenizer_pattern: str | None = None
    """Pre-tokenizer regex (byte_level only)."""

    byte_fallback_start: int | None = None
    byte_fallback_end: int | None = None

    special_tokens: dict[str, int] | None = None

    tool_calling: ToolCallingBlock | None = None
    """Per-model tool-calling convention. Optional; populated by
    ``@codecai/maps-cli`` when it detects a known chat-template signature.
    Absence means the convention is not declared in this map — consult the
    prose table in ``spec/PROTOCOL.md`` § "Tool-call detection without
    decoding"."""

    published_at: str | None = None

    @classmethod
    def from_json(cls, data: bytes | str | dict[str, Any]) -> TokenizerMap:
        """Parse a TokenizerMap from JSON bytes/str/dict and validate it."""
        if isinstance(data, (bytes, bytearray)):
            obj = json.loads(data)
        elif isinstance(data, str):
            obj = json.loads(data)
        else:
            obj = data
        validate(obj)
        tc_obj = obj.get("tool_calling")
        tool_calling: ToolCallingBlock | None = None
        if tc_obj is not None:
            tool_calling = ToolCallingBlock(
                convention=tc_obj["convention"],
                markers=ToolCallingMarkers(
                    start=tc_obj["markers"]["start"],
                    end=tc_obj["markers"]["end"],
                ),
                args_format=tc_obj["args_format"],
                result_format=tc_obj["result_format"],
            )
        return cls(
            id=obj["id"],
            version=str(obj.get("version", "2")),
            vocab_size=int(obj["vocab_size"]),
            vocab=obj.get("vocab"),
            tokens=obj.get("tokens"),
            encoder=obj.get("encoder"),
            merges=obj.get("merges"),
            pre_tokenizer_pattern=obj.get("pre_tokenizer_pattern"),
            byte_fallback_start=obj.get("byte_fallback_start"),
            byte_fallback_end=obj.get("byte_fallback_end"),
            special_tokens=obj.get("special_tokens"),
            tool_calling=tool_calling,
            published_at=obj.get("published_at"),
        )


def validate(obj: Any) -> None:
    """Validate a parsed map dict against the v1/v2 schema."""
    if not isinstance(obj, dict):
        raise TokenizerMapValidationError("not an object")
    if not isinstance(obj.get("id"), str) or not obj["id"]:
        raise TokenizerMapValidationError("id must be a non-empty string")
    if not isinstance(obj.get("version"), str) or not obj["version"]:
        raise TokenizerMapValidationError("version must be a non-empty string")
    if not isinstance(obj.get("vocab_size"), int) or obj["vocab_size"] < 1:
        raise TokenizerMapValidationError("vocab_size must be a positive integer")
    has_vocab = isinstance(obj.get("vocab"), dict) and obj["vocab"]
    has_tokens = isinstance(obj.get("tokens"), dict) and obj["tokens"]
    if not has_vocab and not has_tokens:
        raise TokenizerMapValidationError("one of `vocab` (v2) or `tokens` (v1) is required")
    if obj.get("encoder") not in (None, "byte_level", "metaspace"):
        raise TokenizerMapValidationError(
            f"encoder must be 'byte_level' or 'metaspace' if present, got {obj['encoder']!r}"
        )
    if obj.get("merges") is not None and not isinstance(obj["merges"], list):
        raise TokenizerMapValidationError("merges must be a list of strings")
    bfs = obj.get("byte_fallback_start")
    bfe = obj.get("byte_fallback_end")
    if (bfs is None) != (bfe is None):
        raise TokenizerMapValidationError(
            "byte_fallback_start and byte_fallback_end must both be set or both omitted"
        )
    tc = obj.get("tool_calling")
    if tc is not None:
        if not isinstance(tc, dict):
            raise TokenizerMapValidationError("tool_calling must be an object")
        if tc.get("convention") not in _TOOL_CALLING_CONVENTIONS:
            raise TokenizerMapValidationError(
                f"tool_calling.convention must be one of "
                f"{sorted(_TOOL_CALLING_CONVENTIONS)}, got {tc.get('convention')!r}"
            )
        if tc.get("args_format") not in _TOOL_CALLING_ARGS_FORMATS:
            raise TokenizerMapValidationError(
                f"tool_calling.args_format must be one of "
                f"{sorted(_TOOL_CALLING_ARGS_FORMATS)}, got {tc.get('args_format')!r}"
            )
        if tc.get("result_format") not in _TOOL_CALLING_RESULT_FORMATS:
            raise TokenizerMapValidationError(
                f"tool_calling.result_format must be one of "
                f"{sorted(_TOOL_CALLING_RESULT_FORMATS)}, got {tc.get('result_format')!r}"
            )
        markers = tc.get("markers")
        if not isinstance(markers, dict) or not markers.get("start") or not markers.get("end"):
            raise TokenizerMapValidationError(
                "tool_calling.markers must be an object with non-empty start and end strings"
            )
        # Markers MUST appear as keys in special_tokens (per spec).
        st = obj.get("special_tokens")
        if not isinstance(st, dict) or markers["start"] not in st or markers["end"] not in st:
            raise TokenizerMapValidationError(
                f"tool_calling.markers.start ({markers['start']!r}) and "
                f".end ({markers['end']!r}) must both exist as keys in special_tokens"
            )


# ── Pluggable cache ──────────────────────────────────────────────────────────


class MapCache(abc.ABC):
    """Pluggable cache for loaded maps."""

    @abc.abstractmethod
    async def get(self, key: str) -> TokenizerMap | None:
        ...

    @abc.abstractmethod
    async def set(self, key: str, value: TokenizerMap) -> None:
        ...


class MemoryMapCache(MapCache):
    """Default in-memory cache."""

    def __init__(self) -> None:
        self._store: dict[str, TokenizerMap] = {}

    async def get(self, key: str) -> TokenizerMap | None:
        return self._store.get(key)

    async def set(self, key: str, value: TokenizerMap) -> None:
        self._store[key] = value
