"""v2 (`stages`) pre-tokenizer program tests.

Structured like ``test_pretok_program.py``, which covers v1 (`ops`) only.
This file covers the four v2 stage kinds and the two new/extended ops
schema v2 adds: ``digits_isolate``, ``digit_triples_isolate``,
``punctuation_contiguous``, ``cjk_isolate``, ``punct_ascii_letters``, and
the extended ``letters``/``punct_run`` fields. See
``spec/PRETOKENIZER_PROGRAM.md`` § Stages (v2) and § Op set.

Two oracles back these tests:

1. Direct interpreter unit tests below, hand-derived from the spec's own
   worked examples and stage descriptions.
2. ``packages/pretok-program-conformance/fixtures/pretok-program-cases.json``,
   the cross-language conformance fixture. Its `expected_pieces` values
   were generated by running each program through
   ``packages/web/src/pretok-program.ts`` (the reference v2 executor), not
   hand-typed, so every case here also runs as a fixture-driven
   parametrized test that can't silently drift from the reference.

The full four-model, three-corpus differential audit (golden 125 /
combinatorial-stress 3370 / real-code-and-markdown 460 samples per model)
lives outside this repo in the audit harness that motivated schema v2; see
the project's working history for the exact pass counts. This file is the
in-repo regression net for the stage/op semantics that audit exercised.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from codecai import run_pretok_program

# ── Direct interpreter unit tests: v2 stages ────────────────────────────────


def test_digits_isolate_individual_splits_every_digit():
    prog = {"version": 2, "stages": [{"stage": "digits_isolate", "mode": "individual"}]}
    assert run_pretok_program(prog, "a123b") == ["a", "1", "2", "3", "b"]


def test_digits_isolate_grouped_unbounded_keeps_run_together():
    prog = {"version": 2, "stages": [{"stage": "digits_isolate", "mode": "grouped"}]}
    assert run_pretok_program(prog, "a123b456c") == ["a", "123", "b", "456", "c"]


def test_digits_isolate_grouped_max_run_chunks():
    prog = {"version": 2, "stages": [{"stage": "digits_isolate", "mode": "grouped", "max_run": 3}]}
    assert run_pretok_program(prog, "1234567") == ["123", "456", "7"]


def test_digit_triples_isolate_exact_multiple():
    prog = {"version": 2, "stages": [{"stage": "digit_triples_isolate"}]}
    assert run_pretok_program(prog, "123456") == ["123", "456"]


def test_digit_triples_isolate_leaves_remainder_ungrouped():
    # A run not a multiple of 3 leaves the tail digits as their own piece;
    # the remainder is NOT itself chunked further.
    prog = {"version": 2, "stages": [{"stage": "digit_triples_isolate"}]}
    assert run_pretok_program(prog, "1234567") == ["123", "456", "7"]


def test_digit_triples_isolate_short_run_is_untouched():
    prog = {"version": 2, "stages": [{"stage": "digit_triples_isolate"}]}
    assert run_pretok_program(prog, "12") == ["12"]


def test_punctuation_contiguous_groups_runs_by_class():
    # Whitespace shares the "everything else" bucket with letters, so a
    # whitespace run stays attached to its adjacent letters as one piece.
    prog = {"version": 2, "stages": [{"stage": "punctuation_contiguous"}]}
    assert run_pretok_program(prog, "a  .!b") == ["a  ", ".!", "b"]


def test_cjk_isolate_separates_cjk_from_latin():
    prog = {"version": 2, "stages": [{"stage": "cjk_isolate"}]}
    assert run_pretok_program(prog, "abc日本語def") == ["abc", "日本語", "def"]


def test_cjk_isolate_covers_hiragana_and_katakana():
    prog = {"version": 2, "stages": [{"stage": "cjk_isolate"}]}
    assert run_pretok_program(prog, "ひらがなカタカナ") == ["ひらがなカタカナ"]


# ── Direct interpreter unit tests: new/extended ops ─────────────────────────


def test_op_punct_ascii_letters_matches_glued_apostrophe():
    prog = {"version": 2, "stages": [{"stage": "alternation", "ops": [{"op": "punct_ascii_letters"}]}]}
    assert run_pretok_program(prog, "'m") == ["'m"]


def test_op_punct_ascii_letters_requires_trailing_letter():
    # An ASCII punct char with no following ASCII letter doesn't match;
    # falls through to the unmatched-span case (empty op list here means
    # every position is unmatched, so the whole input is one span).
    prog = {"version": 2, "stages": [{"stage": "alternation", "ops": [{"op": "punct_ascii_letters"}]}]}
    assert run_pretok_program(prog, "'[") == ["'["]


def test_op_letters_lead_other_class_l_p_s_admits_digit():
    # Under l_n (the default) a leading digit would be excluded from the
    # lead-other slot; under l_p_s it's admitted, so the digit and the
    # following letters come out as one piece.
    prog = {
        "version": 2,
        "stages": [{"stage": "alternation", "ops": [
            {"op": "letters", "lead_other": True, "lead_other_class": "l_p_s"},
        ]}],
    }
    assert run_pretok_program(prog, "3abc") == ["3abc"]


def test_op_letters_lead_other_class_l_n_excludes_digit():
    prog = {
        "version": 2,
        "stages": [{"stage": "alternation", "ops": [
            {"op": "letters", "lead_other": True, "lead_other_class": "l_n"},
        ]}],
    }
    # "3" is excluded from the lead-other slot under l_n, so it's an
    # unmatched span on its own; "abc" then matches as its own piece.
    assert run_pretok_program(prog, "3abc") == ["3", "abc"]


def test_op_letters_body_l_m_keeps_combining_mark_attached():
    prog = {"version": 2, "stages": [{"stage": "alternation", "ops": [{"op": "letters", "body": "L_M"}]}]}
    # "e" + combining acute (U+0301) + "x": all one piece under L_M.
    assert run_pretok_program(prog, "éx") == ["éx"]


def test_op_letters_body_default_l_splits_off_combining_mark():
    prog = {"version": 2, "stages": [{"stage": "alternation", "ops": [{"op": "letters"}]}]}
    # Default body is \p{L}+ only; the combining mark doesn't match
    # _is_letter, so it becomes its own unmatched-span piece.
    assert run_pretok_program(prog, "éx") == ["e", "́", "x"]


def test_op_punct_run_charset_p_s_excludes_non_punct_symbol():
    prog = {"version": 2, "stages": [{"stage": "alternation", "ops": [{"op": "punct_run", "charset": "p_s"}]}]}
    assert run_pretok_program(prog, "!@#$") == ["!@#$"]


def test_op_literals_case_sensitive_does_not_fold_case():
    # punct_run is listed ahead of letters here so a failed literals match
    # can't get masked by letters' own lead_other mechanism absorbing the
    # apostrophe anyway: a mismatch must show up as a real split.
    prog = {
        "version": 1,
        "ops": [
            {"op": "literals", "patterns": ["'s", "'t"]},
            {"op": "punct_run"},
            {"op": "letters", "lead_other": True},
        ],
    }
    assert run_pretok_program(prog, "It's") == ["It", "'s"]
    # Case-sensitive: "'S" (capital) must NOT match the "'s" pattern, so
    # the apostrophe and the letter split into separate pieces instead of
    # one contraction token.
    assert run_pretok_program(prog, "It'S") == ["It", "'", "S"]


# ── letters_cased: o200k_base / mistral-nemo cased-letter split ────────────
#
# This op was missing from the Python interpreter entirely until the fix
# these tests accompany. Its absence was invisible in the interpreter's own
# test suite because a v1 alternation with no recognised op simply matched
# nothing at every cursor position and fell through to the unmatched-span
# case, producing one plausible-looking wrong piece instead of an error.
# See the "unrecognised op" tests below for that failure mode directly.


def test_op_letters_cased_title_splits_on_case_boundary():
    # kind: "title" is zero-or-more upper-cluster letters then one-or-more
    # lower-cluster letters, so a camelCase or PascalCase word splits at
    # each boundary where a lowercase run starts.
    prog = {"version": 1, "ops": [{"op": "letters_cased", "kind": "title"}]}
    assert run_pretok_program(prog, "HelloWorld foo") == ["Hello", "World", " ", "foo"]


def test_op_letters_cased_upper_greedy_prefix_absorbs_trailing_lower():
    # kind: "upper" is one-or-more upper-cluster letters then zero-or-more
    # lower-cluster letters. The longest match tries the greediest upper
    # prefix first, so "ABCdef" comes out whole rather than splitting
    # before the lowercase run.
    prog = {"version": 1, "ops": [{"op": "letters_cased", "kind": "upper"}]}
    assert run_pretok_program(prog, "ABCdef XY") == ["ABCdef", " ", "XY"]


def test_op_letters_cased_lead_other_admits_leading_punct():
    prog = {"version": 1, "ops": [{"op": "letters_cased", "kind": "title", "lead_other": True}]}
    assert run_pretok_program(prog, ".Hello") == [".Hello"]


def test_op_letters_cased_trailing_ci_folds_case():
    # trailing_ci matches its patterns with the same ASCII case-fold
    # semantics as literals_ci, so a capitalised contraction like "'S"
    # still matches the lowercase "'s" pattern.
    prog = {"version": 1, "ops": [{"op": "letters_cased", "kind": "title", "trailing_ci": ["'s", "'t"]}]}
    assert run_pretok_program(prog, "It'S") == ["It'S"]


def test_op_letters_cased_o200k_base_shape_splits_camel_case_and_contractions():
    # The exact op list openai/o200k_base and mistralai/mistral-nemo ship:
    # title before upper, both with lead_other and the same trailing_ci
    # contraction list, ahead of numbers/punct_run/newline_block/
    # trailing_ws/ws_run.
    ops = [
        {"op": "letters_cased", "kind": "title", "lead_other": True,
         "trailing_ci": ["'s", "'t", "'re", "'ve", "'m", "'ll", "'d"]},
        {"op": "letters_cased", "kind": "upper", "lead_other": True,
         "trailing_ci": ["'s", "'t", "'re", "'ve", "'m", "'ll", "'d"]},
        {"op": "numbers", "max_run": 3},
        {"op": "punct_run", "lead_space": True, "trailing_chars": "\r\n/"},
        {"op": "newline_block"},
        {"op": "trailing_ws"},
        {"op": "ws_run"},
    ]
    prog = {"version": 1, "ops": ops}
    assert run_pretok_program(prog, "myCamelCaseVariable") == ["my", "Camel", "Case", "Variable"]
    assert run_pretok_program(prog, "HTTP request") == ["HTTP", " request"]
    assert run_pretok_program(prog, "She'll see It's") == ["She'll", " see", " It's"]


# ── The gap-semantics regression ────────────────────────────────────────────
#
# An unmatched span inside an alternation stage must come out as ONE
# piece, not shattered one code point at a time. This is invisible on a
# v1 program (whose op list is exhaustive over raw text) and only
# reachable once an earlier v2 stage has isolated a character class the
# alternation stage's own ops don't handle. See spec/PRETOKENIZER_PROGRAM.md
# § v2 execution.

_DEEPSEEK_THIRD_STAGE_OPS = [
    {"op": "punct_ascii_letters"},
    {"op": "letters", "lead_other": True, "lead_other_class": "l_p_s", "body": "L_M"},
    {"op": "punct_run", "lead_space": True, "trailing_newlines": True, "charset": "p_s"},
    {"op": "newline_block"},
    {"op": "trailing_ws"},
    {"op": "ws_run"},
]


def test_gap_semantics_pure_digit_piece_from_earlier_stage_stays_whole():
    prog = {
        "version": 2,
        "stages": [
            {"stage": "digits_isolate", "mode": "grouped", "max_run": 3},
            {"stage": "alternation", "ops": _DEEPSEEK_THIRD_STAGE_OPS},
        ],
    }
    # digits_isolate first produces ["123", "456"]. The alternation stage's
    # ops have no digit branch, so each piece must pass through whole, NOT
    # get shattered into ["1", "2", "3", "4", "5", "6"].
    assert run_pretok_program(prog, "123456") == ["123", "456"]


def test_gap_semantics_pure_cjk_piece_from_earlier_stage_stays_whole():
    prog = {
        "version": 2,
        "stages": [
            {"stage": "cjk_isolate"},
            {"stage": "alternation", "ops": _DEEPSEEK_THIRD_STAGE_OPS},
        ],
    }
    assert run_pretok_program(prog, "日本語") == ["日本語"]


# ── Versioning: unknown version and unknown stage both raise, never guess ──


def test_unknown_version_raises():
    with pytest.raises(ValueError, match="version"):
        run_pretok_program({"version": 3, "stages": []}, "hello")


def test_unknown_stage_kind_raises():
    with pytest.raises(ValueError, match="stage"):
        run_pretok_program({"version": 2, "stages": [{"stage": "not_a_real_stage"}]}, "hello")


def test_unknown_op_in_v1_alternation_raises_naming_op_and_version():
    # An op kind the interpreter's _MATCHERS table does not recognise must
    # raise rather than silently matching nothing at every position. A
    # silent skip here previously let the alternation scan fall through to
    # the unmatched-span case and emit one plausible-looking wrong piece
    # for the whole input, exactly the failure mode this test guards
    # against. See test_op_letters_cased_* above for the concrete case
    # this bit: letters_cased was unimplemented and matched nothing until
    # the fix these tests accompany.
    with pytest.raises(ValueError, match="not_a_real_op"):
        run_pretok_program({"version": 1, "ops": [{"op": "not_a_real_op"}]}, "hello")
    with pytest.raises(ValueError, match="version 1"):
        run_pretok_program({"version": 1, "ops": [{"op": "not_a_real_op"}]}, "hello")


def test_unknown_op_in_v2_alternation_stage_raises_naming_op_and_version():
    prog = {"version": 2, "stages": [{"stage": "alternation", "ops": [{"op": "not_a_real_op"}]}]}
    with pytest.raises(ValueError, match="not_a_real_op"):
        run_pretok_program(prog, "hello")
    with pytest.raises(ValueError, match="version 2"):
        run_pretok_program(prog, "hello")


def test_unknown_op_does_not_mask_a_real_match_earlier_in_priority_order():
    # The alternation scanner still needs to try every recognised op ahead
    # of the unrecognised one before it can raise: a program is only
    # unusable at a cursor position where none of its recognised ops
    # match either.
    prog = {"version": 1, "ops": [{"op": "letters", "lead_other": True}, {"op": "not_a_real_op"}]}
    assert run_pretok_program(prog, "hello") == ["hello"]


def test_empty_pieces_are_dropped_between_stages():
    # A stage boundary can produce an empty piece where HuggingFace's own
    # Sequence would too; neither runtime should emit a token for it.
    prog = {
        "version": 2,
        "stages": [
            {"stage": "punctuation_contiguous"},
            {"stage": "alternation", "ops": [{"op": "punct_run", "charset": "p_s"}]},
        ],
    }
    out = run_pretok_program(prog, "!!!")
    assert "" not in out


# ── Fixture-driven conformance cases ─────────────────────────────────────────
#
# packages/pretok-program-conformance/fixtures/pretok-program-cases.json is
# the cross-language source of truth for pre_tokenizer_program execution:
# every Codec pretok-program interpreter (TypeScript, Python, Rust, C) must
# reproduce it exactly. Every case there runs here too, so this file can't
# silently fall out of sync with it.

_FIXTURE_PATH = (
    Path(__file__).resolve().parents[2]
    / "pretok-program-conformance" / "fixtures" / "pretok-program-cases.json"
)
_FIXTURE = json.loads(_FIXTURE_PATH.read_text(encoding="utf-8"))


@pytest.mark.parametrize(
    "case", _FIXTURE["cases"], ids=[c["name"] for c in _FIXTURE["cases"]]
)
def test_fixture_case(case):
    got = run_pretok_program(case["program"], case["input"])
    assert got == case["expected_pieces"]
