// SPDX-License-Identifier: MIT
//! Fixture-driven pre_tokenizer_program conformance tests.
//!
//! `packages/pretok-program-conformance/fixtures/pretok-program-cases.json`
//! is the cross-language source of truth for the v1/v2 op and stage
//! contract: every Codec pretok-program interpreter (TypeScript, Python,
//! Rust, C) must reproduce it exactly. Every case there runs here too,
//! generically, so this file can't silently fall out of sync with it the
//! way a hand-mirrored test can. `expected_pieces` in the fixture was
//! generated by running each program through
//! `packages/web/src/pretok-program.ts`, the reference v2 executor, not
//! hand-typed. See `pretok_program.rs`'s own `#[cfg(test)]` module for
//! hand-written Rust-specific tests (error messages, the qwen shortcut
//! test helper); those stay, this is additive.
//!
//! Mirrors `tool_watcher_fixture_tests.rs`'s fixture-loader shape.

use codec_rs::pretok_program::{run_pretok_program, PreTokProgram};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Fixture {
    cases: Vec<Case>,
}

#[derive(Debug, Deserialize)]
struct Case {
    name: String,
    program: PreTokProgram,
    input: String,
    expected_pieces: Vec<String>,
}

fn load_fixture() -> Fixture {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../pretok-program-conformance/fixtures/pretok-program-cases.json"
    );
    let raw = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read fixture at {path}: {e}"));
    serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("failed to parse fixture at {path}: {e}"))
}

#[test]
fn fixture_cases_match_exactly() {
    let fixture = load_fixture();
    assert!(
        !fixture.cases.is_empty(),
        "fixture loaded but has no cases; loader is broken"
    );

    let mut failures: Vec<String> = Vec::new();
    for case in &fixture.cases {
        let actual = run_pretok_program(&case.program, &case.input);
        if actual != case.expected_pieces {
            failures.push(format!(
                "case \"{}\" (input {:?}): actual={:?} expected={:?}",
                case.name, case.input, actual, case.expected_pieces
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "{} fixture case(s) diverged from run_pretok_program output:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
